name = "lightpad"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-12-31"
compatibility_flags = ["nodejs_compat"]

[env.production]
compatibility_date = "2024-12-31"
compatibility_flags = ["nodejs_compat"]
